### ISSUE TITLE
Incorrect cue sheets crash on import

### ISSUE THREAD

**Issue by gh0sti** [OpenEmu/OpenEmu#2891]
happens everytime I try importing this rom from emupara the U version
http://pastebin.com/GbVC9Z3j

**Comment by clobber** [comment]
Nice find, thanks for reporting.

The cue sheet is incorrect. Open the .cue file in a text editor and change the line:
`FILE Dragons_Lair_U.bin BINARY`
to
`FILE "Dragons_Lair_U.bin" BINARY`

If you use TextEdit, copy and paste the line above so that "Smart quotes" don't kick in. Then, save the file and import the .cue file as normal.

**Comment by clobber** [comment]
Fixed in https://github.com/OpenEmu/OpenEmu/commit/597d3ee5d097dc18ab3526bc12395a29e5bea7be

**Comment by gh0sti** [comment]
hey clobber I fixed the cue file like you said and now when i try to import it shows like its going to then doesnt import at all, no crash though.

**Comment by clobber** [comment]
You didn't fix it correctly then, because it imports fine for me. Make sure you are not inserting "smart quotes"
