### ISSUE TITLE
OpenEmu 2.0.4 quits unexpectedly every time, after importing a .m3u file for Sega Saturn (Mednafen Core)

### ISSUE THREAD

**Issue by KelvinPrice** [OpenEmu/OpenEmu#2917]
Hi, 
I updated to Open Emu 2.0.4 experimental with Mednafen core up to date, 0.9.39.2, so I can test and play Sega Saturn games. After loading a .m3u file for a multi disc game into the Sega Saturn library, Open Emu quits unexpectedly the second after, and then every time I try to launch back the app.
Reverting to 2.0.3 seems to fix the problem.
I'm on a iMac 3,4 GHz Intel Core i7 (27 inches, 2011) 8 Go 1333 MHz DDR3 AMD Radeon HD 6970M 1024 M, Os is 10.12.1.

I noticed that the disk switch feature on the Mednafen core appears and is working on the Playstation part, but not on the Saturn one on OpenEmu 2.0.3. I guess it may be related to my problem but I'm not sure... Do you have any idea ?

Please let me know if you need further details.
Thanks in advance for your help

**Comment by clobber** [comment]
Post the crash log. Post the contents of the inside of your m3u and cue sheets.

**Comment by KelvinPrice** [comment]
Sure
![cue m3u contents](https://cloud.githubusercontent.com/assets/16437525/20651064/020bc12e-b4de-11e6-91f6-b4712313c467.png)
[CrashLog.txt](https://github.com/OpenEmu/OpenEmu/files/614927/CrashLog.txt)

Please let me know if you need anything else.

**Comment by clobber** [comment]
This has been fixed in https://github.com/OpenEmu/OpenEmu/commit/136ac9a84f139ec6f6a349fcd4afa9e100a63d23 for next release, probably coming sooner rather than later. Thanks for reporting.

**Comment by pdpd90** [comment]
Hi, the problem isn't solved because we instal the new version 2.0.5 (2.0.5) of Openemu and when we drug in the file m3u the application crush. 

In the attachments you can find the crash log and the file that we try to open.

Thanks

[crash openemu m3u file.zip](https://github.com/OpenEmu/OpenEmu/files/949008/crash.openemu.m3u.file.zip)
![schermata 2017-04-22 alle 15 45 49](https://cloud.githubusercontent.com/assets/27892488/25304977/e104d594-2772-11e7-87e6-dca767e55711.png)
![schermata 2017-04-22 alle 15 46 14](https://cloud.githubusercontent.com/assets/27892488/25304978/e104f8a8-2772-11e7-9256-7fd528c54a02.png)

**Comment by clobber** [comment]
@pdpd90 No...your crash is not related to this one, but completely different and has been fixed for next release.

The issue is obvious: referencing invalid files that don't exist inside your M3U file. Hopefully you figured out that they should be .cue and not .iso
