### ISSUE TITLE
Mayflash N64 Controller Adapter on Mac

### ISSUE THREAD

**Issue by claytonrcarter** [OpenEmu/OpenEmu#2988]
Sorry to repost, but I originally had this as [a comment on an already closed issue](https://github.com/OpenEmu/OpenEmu/issues/2800#issuecomment-269560409).

The adapter has 2 input ports, and the OpenEmu shows 2 "USB GamePad" entries when the adapter is plugged in (even when no controllers are plugged in; see screenshot.) but games seem to only respond to one controller.
![screen shot 2016-12-28 at 6 21 30 pm](https://cloud.githubusercontent.com/assets/1420419/21533642/b672c694-cd2a-11e6-898d-409a75bce56f.png)

The Controls menu receives input from both gamepads and allows me to map buttons, but it appears as though it's reading input from both gamepads as if they were only 1.  (Sorry, it's a little unclear how it all works.)  If I select "Player 1", then the first "USB GamePad", then select "Player 2", then the second "USB GamePad", it all *seems* as though it should work, but only a single controller is recognized in games.  When I unplug and re-plug the adapter (with 2 controllers plugged in), Console displays the following message:
```
12/28/16 6:41:45.746 PM OpenEmu[312]: USB GamePad
12/28/16 6:41:45.759 PM OpenEmu[312]: USB GamePad
```

It seems that above Console output is generated even in only one (or even no) gamepads are plugged in when the adapter is plugged in.  Furthermore, the `- ` before one of the `USB GamePad` entries seems to bounce around between launches.

In case it helps, here is a full Console dump for an exit and relaunch of `OpenEmu`.  (Note that I got several "OpenEmu quit unexpectedly" dialogs and just kept clicking "Reopen" until it worked.  This is unrelated, but has been pretty common behavior for me with OpenEmu: if I just keep trying, it will start to work perfectly!)
```
12/28/16 6:44:42.651 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:42.657 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:42.751 PM com.apple.xpc.launchd[1]: (org.openemu.OpenEmu.108192[522]) Service exited due to signal: Segmentation fault: 11
12/28/16 6:44:42.818 PM com.apple.xpc.launchd[1]: (com.apple.ReportCrash[523]) Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash
12/28/16 6:44:53.186 PM ReportCrash[523]: Saved crash report for OpenEmu[522] version 2.0.4 (2.0.4) to /Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-184453_hakurei.crash
12/28/16 6:44:53.254 PM ReportCrash[523]: Removing excessive log: file:///Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-161836_hakurei.crash
12/28/16 6:44:53.310 PM ReportCrash[523]: AutoSubmitPreference is (null)
12/28/16 6:44:55.231 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:55.237 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:55.325 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000005.OpenEmu[526]) Service exited due to signal: Segmentation fault: 11
12/28/16 6:44:55.920 PM ReportCrash[523]: Saved crash report for OpenEmu[526] version 2.0.4 (2.0.4) to /Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-184455_hakurei.crash
12/28/16 6:44:55.922 PM ReportCrash[523]: Removing excessive log: file:///Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-161839_hakurei.crash
12/28/16 6:44:55.923 PM ReportCrash[523]: AutoSubmitPreference is (null)
12/28/16 6:44:56.653 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:56.659 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:56.748 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000006.OpenEmu[527]) Service exited due to signal: Segmentation fault: 11
12/28/16 6:44:57.088 PM ReportCrash[523]: Saved crash report for OpenEmu[527] version 2.0.4 (2.0.4) to /Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-184457_hakurei.crash
12/28/16 6:44:57.089 PM ReportCrash[523]: Removing excessive log: file:///Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-161841_hakurei.crash
12/28/16 6:44:57.090 PM ReportCrash[523]: AutoSubmitPreference is (null)
12/28/16 6:44:57.748 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:57.755 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:57.847 PM com.apple.xpc.launchd[1]: (com.apple.xpc.launchd.oneshot.0x10000007.OpenEmu[528]) Service exited due to signal: Segmentation fault: 11
12/28/16 6:44:58.179 PM ReportCrash[523]: Saved crash report for OpenEmu[528] version 2.0.4 (2.0.4) to /Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-184458_hakurei.crash
12/28/16 6:44:58.181 PM ReportCrash[523]: Removing excessive log: file:///Users/crcarter/Library/Logs/DiagnosticReports/OpenEmu_2016-12-28-161842_hakurei.crash
12/28/16 6:44:58.181 PM ReportCrash[523]: AutoSubmitPreference is (null)
12/28/16 6:44:58.897 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:58.903 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:59.084 PM sharedfilelistd[306]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:59.087 PM appleeventsd[57]: SecTaskLoadEntitlements failed error=22
12/28/16 6:44:59.122 PM OpenEmu[529]: Apple Keyboard
12/28/16 6:44:59.124 PM OpenEmu[529]: Apple Internal Keyboard / Trackpad
12/28/16 6:44:59.127 PM OpenEmu[529]: Device is already being handled
12/28/16 6:44:59.127 PM OpenEmu[529]: USB GamePad
12/28/16 6:44:59.134 PM OpenEmu[529]: Device is already being handled
12/28/16 6:44:59.134 PM OpenEmu[529]: USB GamePad
12/28/16 6:44:59.136 PM OpenEmu[529]: OELibraryDatabase loadFromURL: 'file:///Users/crcarter/Library/Application%20Support/OpenEmu/Game%20Library/'
12/28/16 6:44:59.416 PM OpenEmu[529]: window did load
12/28/16 6:45:02.199 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:45:02.301 PM launchservicesd[85]: SecTaskLoadEntitlements failed error=22
12/28/16 6:45:32.937 PM mdworker[531]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}
12/28/16 6:45:32.946 PM mdworker[531]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}
12/28/16 6:45:32.966 PM mdworker[532]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}
12/28/16 6:45:32.974 PM mdworker[532]: code validation failed in the process of getting signing information: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)" UserInfo={SecCSArchitecture=i386}
```

Thank you!

**Comment by danielchasehooper** [comment]
I'm also having this issue.

@claytonrcarter Have you found a workaround?

**Comment by Scylla-911** [comment]
I'm having it too...

**Comment by danielchasehooper** [comment]
@clobber Mind shedding a little light on this? I tried digging into it yesterday but it was my first time in the codebase. Seemed like some code was confused that multiple controllers could be coming from the same USB outlet.

**Comment by kjerniga** [comment]
same issue.  @claytonrcarter @danielchasehooper @Scylla-911 - anyone find another solution?  Mario Kart on Sixtyforce works with all 4 controllers, so I think this is a Openemu issue.

**Comment by srpgilles** [comment]
I confirm the issue as well: MarioKart 64 was exhibiting weird behaviour as character selection (each character blinks like mad), and the controls for direction were sloppy. I tried Ocarina of Time, and Link ended up walking very slowly. Following this thread, I attempted SixtyForce, onto which MarioKart runs smoothly. 

However all the mentioned issues aren't related to the Mayflash controller: even if I plug it off and use the keyboard the character selection bug is still there (I tried different MarioKart roms and the issue was always there).

**Comment by TheSuperJez** [comment]
It seems that we will never get support for this Adapter, at least in Mac, not even in RetroArch that has more support... i have been looking for a solution to play my N64 games with an original controller on Mac for months, the only ones i found are using it on Windows with Project64 (it really works like charm...) or as developers wants, use another controller not from Nintendo... if only OSX would have joystick calibration (like in Windows) the problem would be fixed

**Comment by SoloKeita** [comment]
@srpgilles That's correct, it has nothing to do with the N64 controllers or the adapter.  For the Mario Kart 64, that is a known problem with emulators not being able to play the game properly.  You would have the same problem if you were to use GameCube controllers as well.  If you were to play a different game the controllers would work fine.

As for Link walking slowly that is a different problem regarding the Mupen 64 core update and you can read how to "fix" it [here](https://github.com/OpenEmu/OpenEmu/issues/3102)

**Comment by SoloKeita** [comment]
@TheSuperJez I had my N64 controllers working with Sixtyforce on my mac.  So it is indeed possible.  This is a bug with OpenEmu itself.  You can't get the controllers working with any of the cores in OpenEmu which means it's not Mupen64 but something with OpenEmu.

**Comment by peterfication** [comment]
For me this happens as well but with different adapters.

I bought two [raphnet N64 dual adapters](http://www.raphnet-tech.com/products/dual_n64_to_usb_adapter/index.php). All 4 connected controllers are shown correctly in the controllers configuration and their buttons can be configured. However, when I start a game, only 2 of the controllers are working (one for each adapter).

I tested the adapters/controllers with [sixtyforce](http://sixtyforce.com/) and it worked fine. Also with [Controllers Lite](https://itunes.apple.com/us/app/controllers-lite/id673660806?mt=12) there was no problem in getting the adapters/controllers to work.

**Comment by northamerican** [comment]
^ if anyone tries the controllers app described above as a way to get around the issue, don't. openemu still wrongly reads n64 controller presses, even when configured for controllers.app's 'keyboard'.

**Comment by benjofisch** [comment]
Just chiming in to say I am having issues as well using just one N64 controller with the Mayflash adapter. Once I do find the correct USB port and am able to get Majora's Mask started, the analog stick is having the issues described above: very limited range which results in slow walking. From the linked thread it sounded like this was addressed and patched already, but maybe I'm misunderstanding.

Is there a fix planned for this?

**Comment by clobber** [comment]
Issues using Mayflash adapters have been addressed in OpenEmu 2.2.

**Comment by SoloKeita** [comment]
Thank you so much @clobber!!!  You're an absolute LEGEND!!

**Comment by benjofisch** [comment]
Unfortunately I am still having issues with version 2.2 

Whereas before I could input all of the buttons, but had limited analog stick range, now I cannot even properly map the buttons. The first issue I had was when assigning the analog-up direction. It mapped it, auto-assigned analog-down to the inverse, and then almost instantly assigned the next setting, analog-left. I had to just barely tap it to get it to finally work, but then it would only intermittently map the other buttons.

Running macOS Catalina 10.15.2 on a mid-2014 MBP // Open Emu 2.2 with Mayflash N64 Controller Adapter

Thank you for looking into these issues!

**Comment by clobber** [comment]
>The first issue I had was when assigning the analog-up direction. It mapped it, auto-assigned analog-down to the inverse, and then almost instantly assigned the next setting, analog-left.

The new analog axis auto-calibration system is causing sensitivity issues, affecting the dead zone of the analog axes.

**Comment by clobber** [comment]
@benjofisch Please test this build to see if it resolves your issue of mapping the analogs:

https://send.firefox.com/download/4f2509ab0285bff0/#pPaiwLm2QpGQpd-LcKoKWg

**Comment by benjofisch** [comment]
Works great! Brilliant! Happy new year

**Comment by northamerican** [comment]
@clobber can we have the link to the fixed build again? i see we're still on 2.2. thanks

**Comment by clobber** [comment]
Issues using the adapter with OpenEmu 2.2 have been fixed in OpenEmu 2.2.1, available now.
