### ISSUE TITLE
Can't open the program, get error: Foundation._GenericObjCError error 0.

### ISSUE THREAD

**Issue by Magic1MrFox** [OpenEmu/OpenEmu#3450]
Hi,
I had OpenEmu working a few ago but recently updated my Mac. Recently, whenever I tried to play a GBA game, it would freeze after a couple minutes. As a result, I uninstalled the app and reinstalled the latest version. However, now when trying to open it, I receive following message.

The operation couldn't be completed.
(Foundation._GenericObjCError error 0.)

OpenEmu just closes after the message. I have tried other versions but keep receiving the same error. Any help is appreciated.

Thank you

**Comment by clobber** [comment]
The freeze was a bug in macOS 10.13 that we fixed in OpenEmu 2.0.6.1.

Your error sounds like #3044 to me.

**Comment by Magic1MrFox** [comment]
The issue was not the freeze. The issue was the inability to open the program.
Furthermore, I've also attempted what's been covered in #3044, and it also did not fix the problem.

Help would be appreciated.

**Comment by clobber** [comment]
Cannot help you beyond what is in #3040 and other related issues referenced to it, so I suggest you actually read through them. Do not open another issue for this.

**Comment by Magic1MrFox** [comment]
What do Japanese strings have to do with the issue?
If you can't help that's fine.
